const META = 21000;
const STORAGE_KEY = 'ingresosDiariosExtra';
const HISTORICAL_KEY = 'ingresosDataHistorica';
const UNIFIED_KEY = 'ingresosRegistrosUnificados';
const LAST_BACKUP_KEY = 'ingresosUltimoBackupCompleto';
const PRE_IMPORT_BACKUP_KEY = 'ingresosBackupAntesDeImportar';
const PROJECTS_KEY = 'trabajosProyectosRegistros';
const PASSWORD_FILE = 'pseleminar.txt';
const dataBase = [];

window.META = META;
window.STORAGE_KEY = STORAGE_KEY;
window.HISTORICAL_KEY = HISTORICAL_KEY;
window.UNIFIED_KEY = UNIFIED_KEY;
window.LAST_BACKUP_KEY = LAST_BACKUP_KEY;
window.PRE_IMPORT_BACKUP_KEY = PRE_IMPORT_BACKUP_KEY;
window.PROJECTS_KEY = PROJECTS_KEY;
window.PASSWORD_FILE = PASSWORD_FILE;
window.dataBase = dataBase;
