(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"index_atlas_1", frames: [[0,0,596,1280]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.A7x15centimetros_00136 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.an_Video = function(options) {
	this.initialize();
	this._element = new $.an.Video(options);
	this._el = this._element.create();
}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,400,300);

p._tick = _tick;
p._handleDrawEnd = _handleDrawEnd;
p._updateVisibility = _updateVisibility;
p.draw = _componentDraw;



(lib.Symbol13 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(12.1,1,1).p("AiJCXIAAktIETAA");
	this.shape.setTransform(13.775,15.05);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol13, new cjs.Rectangle(-6,-6,39.6,42.1), null);


(lib.Symbol10 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(12.1,1,1).p("AiaiWIE1AAIAAEt");
	this.shape.setTransform(15.525,15.05);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol10, new cjs.Rectangle(-6,-6,43.1,42.1), null);


(lib.Symbol7 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(153,153,153,0.988)").s().p("EghDALjIAA3FMBCHAAAIAAXFg");
	this.shape.setTransform(3.175,-0.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol7, new cjs.Rectangle(-208.4,-74.7,423.20000000000005,147.8), null);


(lib.Symbol12 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(12.1,1,1).p("ACKClIkTAAIAAlJ");
	this.shape.setTransform(13.775,16.475);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol12, new cjs.Rectangle(-6,-6,39.6,45), null);


(lib.Symbol11 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(12.1,1,1).p("ACbikIAAFJIk1AA");
	this.shape.setTransform(15.525,16.475);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol11, new cjs.Rectangle(-6,-6,43.1,45), null);


(lib.Symbol8 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhTBlQgdgoAAg+QAAg7AegoQAdgoAzAAQA3AAAeAlQAeAkAABCQAABCgeAmQgfAlg2AAQg0AAgdgngAg3hOQgSAcAAAxQAAAtATAgQARAfAjAAQAkAAAVgdQATgcAAgzQAAhqhMABQgjgBgSAdg");
	this.shape.setTransform(232.6,47.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhQCIIAAkPIChAAIAAAhIh8AAIAABMIBZAAIAAAeIhZAAIAABiIB6AAIAAAig");
	this.shape_1.setTransform(210.35,47.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AheCJIAAkPIBDgCQA4AAAhAjQAhAiAAA6QAACSiHAAgAg5hlIAADKQANACASAAQAmAAAWgdQAWgdAAgzQAAhhhVAAIgcACg");
	this.shape_2.setTransform(188.5,47.825);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgSCIIAAkPIAkAAIAAEPg");
	this.shape_3.setTransform(170.9,47.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgHCKIhlkTIApAAIBFDIIBDjIIAoAAIhiETg");
	this.shape_4.setTransform(154.475,48.075);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AA1CJIhHh0IgngCIAAB2IgmAAIAAkPIAdgBIAngBQBhAAAABOQAAAZgPAVQgQATgWAFIBPB9gAg5hkIAABYQANACANAAQAgAAAPgLQAPgLAAgbQAAgXgQgKQgPgKgkAAIgVACg");
	this.shape_5.setTransform(122.275,47.775);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhQCIIAAkPIChAAIAAAhIh8AAIAABMIBYAAIAAAeIhYAAIAABiIB6AAIAAAig");
	this.shape_6.setTransform(100.3,47.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHCKIhlkTIApAAIBFDIIBDjIIAoAAIhiETg");
	this.shape_7.setTransform(78.275,48.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(50));

	// Symbol_13
	this.instance = new lib.Symbol13();
	this.instance.setTransform(13.8,15.1,1,1,0,0,0,13.8,15.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-17.7,y:-16.4},24,cjs.Ease.get(1)).to({x:13.8,y:15.1},25,cjs.Ease.get(-1)).wait(1));

	// Symbol_12
	this.instance_1 = new lib.Symbol12();
	this.instance_1.setTransform(13.8,80.1,1,1,0,0,0,13.8,16.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:-17.7,y:111.6},24,cjs.Ease.get(1)).to({x:13.8,y:80.1},25,cjs.Ease.get(-1)).wait(1));

	// Symbol_11
	this.instance_2 = new lib.Symbol11();
	this.instance_2.setTransform(295.75,80.1,1,1,0,0,0,15.5,16.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:327.25,y:111.6},24,cjs.Ease.get(1)).to({x:295.75,y:80.1},25,cjs.Ease.get(-1)).wait(1));

	// Symbol_10
	this.instance_3 = new lib.Symbol10();
	this.instance_3.setTransform(295.75,15.1,1,1,0,0,0,15.5,15.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:327.25,y:-16.4},24,cjs.Ease.get(1)).to({x:295.75,y:15.1},25,cjs.Ease.get(-1)).wait(1));

	// Layer_1
	this.instance_4 = new lib.Symbol7();
	this.instance_4.setTransform(154.05,48.5,0.6974,0.5441,0,0,0,0,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(50));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-73,-37.5,458.6,171.7);


// stage content:
(lib.duran = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,1];
	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		this.bt.addEventListener("click", fl_MouseClickHandler.bind(this));
		
		function fl_MouseClickHandler()
		{
		this.play();
		}
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Actions
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhZBjQgQgJAAgOQAAgLALgJQAMgJAXgFQALgDAMgBIAXgDIgFgRIgIgZIgHgcIgHASIgMAVIgOgGQAIgNAHgPIANgeQAKgZARgNQAQgMAZABIAIAAIAJABQALABAEAHQAFAFAAAIQgBAIgDAGQgEAGgIAAQgEAAgGgDQgFgBgEgBQgIAAgEAGQgEAEgBAEIgBAFIAAAGQAAAMAFASIAMArIABgBQAKgCAMgEQALgFAKgIQALgHAGgOIACgBIADgBIAGACQADADAAADIgBABQgKAVgTANQgUAMgWAEIAAADQAAAYgLAPQgLAOgPAHQgRAFgTAAQghgCgRgJgAgVA2IgSABIgTAEQgOADgHAFQgGAEAAAEQAAAGAGADQAGAEAJACQAKADAKAAQAPABALgHQALgGAAgQIAAgGIgCgHIgMACg");
	this.shape.setTransform(856.725,156.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhOBcQgRgSgBgkQABgaAJgZQALgaAQgWQAQgWAUgMQAUgNAUgBQAMAAAIAHQAKAFAEAJQAFAJgBAKQAAARgLAPQgKAQgQAMQgQALgRAJQgQAJgOACIAAABIAAAJIgBAJQABAZAIAMQAHALANgBQAPAAAOgMQAQgMAOgRQAOgRALgRQALgQAFgKIACgCIADAAQADAAADACQACACABADIgBACQgJARgOAVQgMAUgQARQgQASgTALQgTALgXABQgcgBgSgRgAAIhKQgIAGgLANQgKAOgHAPQgIAQgEAMIgCAEQAJgDAOgGQANgHANgKQAOgKAIgLQAKgLAAgMQAAgGgEgFQgDgFgHAAIgCAAQgGAAgJAGg");
	this.shape_1.setTransform(842.45,156.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgKBjQgIgKABgRQAAgTAHgYQAHgXAIgWQALgYAKgTIAPgeQgMAIgQARQgPASgRAXQgRAWgPAXQgQAYgLAVQgMAUgEAMQgDAFgDADQgEACgEAAQgKAAgHgHQgHgIgBgHIAAgCQAFgZAHgaQAHgaAJgXQAIgYAJgSQAHgTAGgJQAJgMAJgGQAKgGAIAAQAFAAADACQADADAAAFQAAAFgHAQIgRAtQgLAdgNAnQAXgmAXghQAZggAWgUQAWgUARgBQANAAAGAEQAJAEAAAJIgBAFIgCAGIgNAhIgSAvQgIAZgGAWQgHAXAAAMQgBAGACABQAAABABAAQAAAAAAABQABAAAAAAQABAAAAAAQAHAAAJgJQAKgJAKgNIAWgdIATgbIAKgRIACgCIADAAQADAAADACQADACAAADIAAACIgSAdQgMASgPATQgPAUgQAOQgQAOgPACIgGABIgGAAQgRAAgIgLg");
	this.shape_2.setTransform(821.9,156.125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag3BmQgLgIgFgNQgFgMABgPQAAgXAHgWQAIgVAKgOQADgFAGgDQAHgCAHAAQALAAAHAEQAIADABAJIgBAFQgGAFgHAOQgHAPgGARQgFASAAAPQgBAMAEAFQAEAFAJAAQAOAAALgLQAMgMAIgSQAJgSAGgUQAEgUABgSQAAgTgHgNQgGgMgOgBQgJABgIAEQgIAEgDAHQgEAFgGACQgGACgGAAQgJAAgHgEQgGgDAAgIQAAgIAHgJQAIgKAMgIQAJgGALgDQAJgEAKAAQAgACAOAUQAPASAAAgQgBAYgIAZQgIAagOAWQgPAWgSAOQgSANgWABQgRgBgLgHg");
	this.shape_3.setTransform(800.9477,156.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAuBmQgMgDgMgBQgQABgQADIghAFQgQADgNAAQgSgBgIgHQgIgJAAgNQAAgRANgWQANgUAUgVQATgUAWgRQAUgSARgKQARgLAIAAIgQgDQgMgCgOAAQgPAAgQAEQgPACgNAJQgMAIgGAQQABgbAJgPQAIgPAOgFQAOgGAQAAQAPABARACIAgAFQAQADAMABIALgBQAFgBAEgDIACAAIABgBQABAAABAAQAAAAABABQAAAAABAAQAAABAAAAQACAEAAAEQAAAJgEAKQgDAMgHAJQgHAKgIACQgLADgRALQgRALgUAPQgRAPgSAQQgSAQgKAPQgLAOAAAJQAAABAAABQAAAAAAABQAAAAAAABQABAAAAAAQABACADABQAIgBAPgGIAfgPQAQgGAQgBQAMAAAJAGQAIAHAFAOIABAEIABAJIgBAEIAAAGQgIgHgLgCg");
	this.shape_4.setTransform(783.65,156.15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgNBlQgIgLAAgRIAAgLIACgMQgKARgLANQgMANgLAJQgMAHgLABQgYgBgKgPQgKgPABgYQAAgSAEgSQAEgTAGgPQAFgRAFgKQAOgaAOgPQAOgPAOgHQAPgGAQAAQARAAAOAHQAPAHAIAPQAIgNAJgGQAKgHAJAAQAFAAADADQADACAAAGIgGATIgOAlIgRAsIgPAsQgGAWAAANIABAIIAEACQAGgBAJgJQAKgIALgOIAVgcIATgbIALgRIACgCIACgBQAEAAACADQAEACAAADIgBACIgRAcQgMATgPATQgPATgRAOQgQAOgPADIgLABQgSgBgHgKgAgbhSQgMANgKAVQgKAVgIAYQgHAXgFAVQgEAVAAAOQAAAHABAEQABAEADABIAAAAQAIgBAMgOQAMgOAOgWIAagsQAMgXAJgTIABgBIAOgbQgGgLgJgGQgIgGgIAAQgOABgMANg");
	this.shape_5.setTransform(763.5488,155.975);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhfBmQgIgHAAgIIAAgCQAEgYAIgaQAHgaAIgXQAJgYAIgTQAIgSAGgJQAIgNAKgGQAKgGAIAAQAFAAADADQACADAAAFQgBAHgMAgQgNAggUA6QAWgoAWggQAVgfAVgSQAUgSASgBQALAAAHAFQAHAEAAAJQAAAFgEAJIgIAXQgEAMAAALQAAAGABACQABADAEABIgNADIgLAAQgNAAgIgFQgHgFAAgMQAAgJAFgMQAFgMAKgRQgMAIgPARQgPARgPAWQgPAXgNAWQgOAXgKAUIgPAfQgDAIgEADQgEAEgFAAQgKgBgHgHg");
	this.shape_6.setTransform(739.625,156.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag3BmQgLgIgFgNQgFgMABgPQAAgXAHgWQAIgVAKgOQADgFAGgDQAHgCAHAAQALAAAHAEQAIADABAJIgBAFQgGAFgHAOQgHAPgGARQgFASAAAPQgBAMAEAFQAEAFAJAAQAOAAALgLQAMgMAIgSQAJgSAGgUQAEgUABgSQAAgTgHgNQgGgMgOgBQgJABgIAEQgIAEgDAHQgEAFgGACQgGACgGAAQgJAAgHgEQgGgDAAgIQAAgIAHgJQAIgKAMgIQAJgGALgDQAJgEAKAAQAgACAOAUQAPASAAAgQgBAYgIAZQgIAagOAWQgPAWgSAOQgSANgWABQgRgBgLgHg");
	this.shape_7.setTransform(721.5977,156.025);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhhC0QgUgNgLgYQgMgYAAgjQAAgfALglQAKgkAUglQASglAageQAZgfAegSQAdgTAhAAIALAAIANACQARAFAIAOQAIAOAAATQgBAagKAdQgLAegSAaQgRAbgWAQQgWARgUAAQgLABgLgGQgKgGgJgMIAEAAQAOAAARgLQAQgMARgUQARgTAOgXQAPgWAIgVQAJgWAAgPQAAgKgEgGQgEgGgJAAQgWAAgWATQgWATgVAfQgUAfgRAmQgRAmgKAkQgKAmAAAgQAAAdAJATQAKASAVADIAJAAQAeAAAYgQQAagQAWgYQAWgYAQgaQARgaAMgWIABgBIADAAQADAAADACQACACABADIAAACQgNAbgSAdQgTAdgYAYQgZAZgdAPQgdAQghAAQgbAAgVgNg");
	this.shape_8.setTransform(702.95,152.525);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhZBjQgQgJAAgOQAAgLALgJQAMgJAXgFQALgDAMgBIAXgDIgFgRIgIgZIgHgcIgHASIgMAVIgOgGQAIgNAHgPIANgeQAKgZARgNQAQgMAZABIAIAAIAJABQALABAEAHQAFAFAAAIQgBAIgDAGQgEAGgIAAQgEAAgGgDQgFgBgEgBQgIAAgEAGQgEAEgBAEIgBAFIAAAGQAAAMAFASIAMArIABgBQAKgCAMgEQALgFAKgIQALgHAGgOIACgBIADgBIAGACQADADAAADIgBABQgKAVgTANQgUAMgWAEIAAADQAAAYgLAPQgLAOgPAHQgRAFgTAAQghgCgRgJgAgVA2IgSABIgTAEQgOADgHAFQgGAEAAAEQAAAGAGADQAGAEAJACQAKADAKAAQAPABALgHQALgGAAgQIAAgGIgCgHIgMACg");
	this.shape_9.setTransform(666.225,156.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag3BmQgLgIgFgNQgFgMABgPQAAgXAHgWQAIgVAKgOQADgFAGgDQAHgCAHAAQALAAAHAEQAIADABAJIgBAFQgGAFgHAOQgHAPgGARQgFASAAAPQgBAMAEAFQAEAFAJAAQAOAAALgLQAMgMAIgSQAJgSAGgUQAEgUABgSQAAgTgHgNQgGgMgOgBQgJABgIAEQgIAEgDAHQgEAFgGACQgGACgGAAQgJAAgHgEQgGgDAAgIQAAgIAHgJQAIgKAMgIQAJgGALgDQAJgEAKAAQAgACAOAUQAPASAAAgQgBAYgIAZQgIAagOAWQgPAWgSAOQgSANgWABQgRgBgLgHg");
	this.shape_10.setTransform(649.8477,156.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhfBmQgIgHAAgIIAAgCQAEgYAIgaQAHgaAIgXQAJgYAIgTQAIgSAGgJQAIgNAKgGQAKgGAIAAQAFAAADADQACADAAAFQgBAHgMAgQgNAggUA6QAWgoAWggQAVgfAVgSQAUgSASgBQALAAAHAFQAHAEAAAJQAAAFgEAJIgIAXQgEAMAAALQAAAGABACQABADAEABIgNADIgLAAQgNAAgIgFQgHgFAAgMQAAgJAFgMQAFgMAKgRQgMAIgPARQgPARgPAWQgPAXgNAWQgOAXgKAUIgPAfQgDAIgEADQgEAEgFAAQgKgBgHgHg");
	this.shape_11.setTransform(631.725,156.075);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhECgQgIgLABgSQAAgQAFgSQAEgUAIgTQAIgaALgcIAVg1IATguIgTAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBgBAAAAIAAgDIABgHQACgEACgBIAXAAIALgVIAHgMQAIgMAJgHQAKgGAIAAQAFAAADACQADADAAAFIgBAGIgCAGIgOAjIALAAIAGABIACACIAAADQAAAEgCAEQgCADgDAAIgSAAIgSAtIgVA1IgSA3QgJAbgGAWQgFAVAAAMQAAAGABABQAAABABAAQAAABABAAQAAAAABABQAAAAABAAQAFAAAKgKQAIgIALgOIAWgcIASgbIALgSIACgCIADAAQADAAADACQADACAAADIAAACIgSAeQgMASgPATQgPAUgQAOQgQAOgOACIgGABIgGAAQgSgBgIgJg");
	this.shape_12.setTransform(617.8735,150.15);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhZBjQgQgJAAgOQAAgLALgJQAMgJAXgFQALgDAMgBIAXgDIgFgRIgIgZIgHgcIgHASIgMAVIgOgGQAIgNAHgPIANgeQAKgZARgNQAQgMAZABIAIAAIAJABQALABAEAHQAFAFAAAIQgBAIgDAGQgEAGgIAAQgEAAgGgDQgFgBgEgBQgIAAgEAGQgEAEgBAEIgBAFIAAAGQAAAMAFASIAMArIABgBQAKgCAMgEQALgFAKgIQALgHAGgOIACgBIADgBIAGACQADADAAADIgBABQgKAVgTANQgUAMgWAEIAAADQAAAYgLAPQgLAOgPAHQgRAFgTAAQghgCgRgJgAgVA2IgSABIgTAEQgOADgHAFQgGAEAAAEQAAAGAGADQAGAEAJACQAKADAKAAQAPABALgHQALgGAAgQIAAgGIgCgHIgMACg");
	this.shape_13.setTransform(603.275,156.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhOBcQgRgSgBgkQABgaAJgZQALgaAQgWQAQgWAUgMQAUgNAUgBQAMAAAIAHQAKAFAEAJQAEAJAAAKQAAARgKAPQgLAQgQAMQgRALgQAJQgQAJgNACIAAABIgBAJIgBAJQABAZAIAMQAHALANgBQAPAAAOgMQAQgMAOgRQAOgRALgRQALgQAFgKIACgCIADAAQADAAADACQADACAAADIgBACQgKARgNAVQgMAUgQARQgQASgTALQgTALgXABQgdgBgRgRgAAIhKQgIAGgLANQgKAOgHAPQgIAQgEAMIgCAEQAKgDANgGQANgHANgKQAOgKAIgLQAKgLAAgMQAAgGgDgFQgEgFgHAAIgCAAQgGAAgJAGg");
	this.shape_14.setTransform(589,156.05);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgJBkQgIgLAAgRIABgOIADgOIgYAeQgNAOgNAKQgNAJgMACIgLABQgTAAgHgKQgJgLABgRQAAgUAHgXQAHgYAKgWQAKgXAJgSIAQgbQAHgMAKgGQAKgGAIAAQAFAAADACQACADAAAFQAAAEgGAPIgOAlIgRAtQgIAXgGAVQgFAVgBAOIABAHQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAQAIAAAMgOQANgNAOgSIAZgjQAKgQAEgIQAKgYAKgTIAQgcQAHgMAKgGQAKgGAIAAQAFAAADACQACADABAFIgGATIgPAlIgRAtIgOAsQgFAVgBAOQAAAFACACQAAABAAAAQAAAAABABQAAAAABAAQAAAAABAAQAGAAAJgJQAKgJALgNIAVgdIATgbIALgRIACgCIACAAQAEAAACACQADACABADIgBACIgRAdQgMASgPATQgPAUgRAOQgQAOgPACIgFABIgGAAQgSAAgHgKg");
	this.shape_15.setTransform(568.3986,156.125);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ai8DDQgMgGgIgNQgHgOgBgWQAHAPAIAHQAJAHALAAQATgBAVgTQAWgTAUggQAVggASgnIANgbIAPgqIAQgvQAGgYAFgVQAEgUABgOQAAgKgDgDQgCgCgEAAQgMAAgPAMQgQAMgQATQgRAUgOAYQgOAXgKAXQgIAXgBAUIABAFIAAAFQgTgDgJgLQgKgMAAgSQAAgWANgbQANgaAXgZQAXgZAfgQQAggQAkgBQALAAAHADQAGADADAHQAKAQAFAaQAGAaADAgIAGBDIAFBBQADAgADAZQAIgfAMgkIAXhGIAZhBIAUgyIAOgbQAHgMAKgGQAJgGAJAAQAEAAADACQADADABAFIgBAFIgCAHIgKAZIgUA3IgXBIIgaBMIgWBGQgJAfgEASQgDAKgEAEQgFAEgFAAIgIgBIgIgFQgIgFgFgSQgHgSgEgcIgIg7IgHhCIgHhAQgIAegKAcQgIAcgMAaQgNAhgQAeQgRAegTAXQgTAXgUANQgVAOgWAAIgCAAQgMAAgLgGg");
	this.shape_16.setTransform(538.5,153.1519);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgKBjQgIgKAAgRQABgTAHgYQAGgXAKgWQAJgYAKgTIAQgeQgMAIgPARQgQASgRAXQgRAWgPAXQgQAYgLAVQgLAUgFAMQgDAFgDADQgEACgEAAQgKAAgHgHQgIgIAAgHIAAgCQAEgZAIgaQAHgaAJgXQAIgYAIgSQAJgTAGgJQAIgMAJgGQAKgGAIAAQAFAAADACQADADAAAFQgBAFgGAQIgSAtQgKAdgNAnQAWgmAZghQAYggAVgUQAXgUASgBQALAAAIAEQAHAEABAJIgBAFIgCAGIgNAhIgRAvQgKAZgGAWQgGAXAAAMQAAAGABABQAAABABAAQAAAAAAABQABAAAAAAQABAAAAAAQAHAAAJgJQAJgJALgNIAWgdIATgbIAKgRIACgCIADAAQADAAADACQADACAAADIgBACIgRAdQgMASgPATQgPAUgQAOQgQAOgPACIgGABIgGAAQgRAAgIgLg");
	this.shape_17.setTransform(491.3,156.125);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhOBcQgRgSgBgkQABgaAJgZQALgaAQgWQAQgWAUgMQAUgNAUgBQAMAAAIAHQAKAFAEAJQAEAJAAAKQAAARgKAPQgLAQgQAMQgRALgQAJQgQAJgNACIAAABIgBAJIgBAJQABAZAIAMQAHALANgBQAPAAAOgMQAQgMAOgRQAOgRALgRQALgQAFgKIACgCIADAAQADAAADACQADACAAADIgBACQgKARgNAVQgMAUgQARQgQASgTALQgSALgYABQgdgBgRgRgAAIhKQgIAGgLANQgKAOgHAPQgIAQgEAMIgCAEQAKgDANgGQANgHANgKQAOgKAIgLQAKgLAAgMQAAgGgDgFQgEgFgHAAIgCAAQgGAAgJAGg");
	this.shape_18.setTransform(472.45,156.05);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhNBcQgSgSAAgkQAAgaAJgZQALgaAQgWQAQgWAUgMQAUgNATgBQANAAAJAHQAIAFAFAJQAEAJABAKQgBARgKAPQgLAQgQAMQgRALgPAJQgSAJgMACIAAABIgCAJIAAAJQACAZAGAMQAIALAOgBQAOAAAPgMQAPgMAOgRQAOgRALgRQALgQAFgKIACgCIACAAQAEAAADACQACACAAADIAAACQgJARgNAVQgNAUgQARQgQASgTALQgSALgYABQgdgBgQgRgAAIhKQgIAGgLANQgKAOgIAPQgHAQgEAMIgBAEQAJgDANgGQAOgHAMgKQANgKAKgLQAJgLAAgMQAAgGgDgFQgEgFgIAAIgBAAQgGAAgJAGg");
	this.shape_19.setTransform(443.35,156.05);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AhfBmQgIgHAAgIIAAgCQAEgYAIgaQAHgaAIgXQAJgYAIgTQAIgSAGgJQAIgNAKgGQAKgGAIAAQAFAAADADQACADAAAFQgBAHgMAgQgNAggUA6QAWgoAWggQAVgfAVgSQAUgSASgBQALAAAHAFQAHAEAAAJQAAAFgEAJIgIAXQgEAMAAALQAAAGABACQABADAEABIgNADIgLAAQgNAAgIgFQgHgFAAgMQAAgJAFgMQAFgMAKgRQgMAIgPARQgPARgPAWQgPAXgNAWQgOAXgKAUIgPAfQgDAIgEADQgEAEgFAAQgKgBgHgHg");
	this.shape_20.setTransform(422.575,156.075);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhlDKQgJAAgJgIQgIgIAAgHIAAgBQABgWAHghQAIggALgmQALglANglQANgmANggIAVg2QAJgWAEgHQAHgMAJgGQAKgGAIAAQAFAAADADQADADAAAFIAAAFIgCAGIgGAOIgKAeQALgSAMgQQANgPAMgKQANgKANAAQAYABAJAPQAKAPAAAXQAAASgFATQgDATgGAQQgGAQgFAKQgNAagOAQQgOAOgOAGQgPAGgQAAQgPAAgMgFQgNgFgJgJIgXBJIgTBBIgLAuQgCAKgEAEQgEAEgFAAIgBAAgAA8isQgKAKgLARIgWAjIgUAkIgNAcIgMAiQAHAJAHADQAHAEAHAAQANAAAMgNQANgMAKgVQAKgVAIgYQAHgXAFgWQAEgVAAgOQAAgJgBgDQgCgEgDAAQgGAAgKALg");
	this.shape_21.setTransform(400.3512,165.0028);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAtBkQgJgLABgRQAAgTAHgXQAHgXAJgWQAKgWAKgTIAPgdQgNAIgQARQgQATgRAXQgSAWgPAYQgPAXgKAUQgMAUgEAKIgDAGQgDACgDAAQgJAAgHgLQgGgLgBgQQABgTAGgYQAHgXAKgXIATgqIAQgeQgMAIgQASQgQARgRAXIggAtIgaArQgLAUgEALIgBABIgBACQgDAGgDACQgEADgEgBQgKAAgHgIQgIgHAAgHIAAgCQAEgYAIgaQAHgaAJgYQAIgYAIgSQAJgSAFgKQAJgMAJgGQAKgGAIAAQAFAAADACQADADAAAGQgBAEgGAQIgSAtQgKAdgNAoQAWgnAYggQAZghAWgUQAYgUAQgBQAMAAAHAEQAIAEAAAKIgBAEIgCAGIgNAiIgLAdIgMAkQATgeAWgdQAWgdAVgSQAUgSAPgBIAFgBQAMAAAGAEQAIAFAAAJIgBAEIgBAGIgOAhIgRAwQgJAYgGAWQgGAXgBAMIABAIQABAAAAABQAAAAABAAQAAABABAAQABAAABAAQAFAAAJgKQAKgIALgNIAWgdIASgbIALgSIACgCIADAAIAFACQAEADAAADIAAABIgSAdQgMASgPAUQgPATgRAOQgPAOgPADIgLABQgUgBgHgKg");
	this.shape_22.setTransform(378.1,156.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AhOBcQgRgSgBgkQABgaAJgZQALgaAQgWQAQgWAUgMQAUgNAUgBQAMAAAIAHQAKAFAEAJQAEAJAAAKQAAARgKAPQgLAQgQAMQgRALgQAJQgQAJgNACIAAABIgBAJIgBAJQABAZAIAMQAHALANgBQAPAAAOgMQAQgMAOgRQAOgRALgRQALgQAFgKIACgCIADAAQADAAADACQADACAAADIgBACQgKARgNAVQgMAUgQARQgQASgTALQgTALgXABQgdgBgRgRgAAIhKQgIAGgLANQgKAOgHAPQgIAQgEAMIgCAEQAKgDANgGQANgHANgKQAOgKAIgLQAKgLAAgMQAAgGgDgFQgEgFgHAAIgCAAQgGAAgJAGg");
	this.shape_23.setTransform(353.65,156.05);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AhDCTQgJgLABgRQAAgUAHgYQAHgXAKgXQAJgXAKgRIAPgbQAIgMAJgGQAKgGAIAAQAFAAADACQACADAAAGQAAADgGAQIgOAkIgQAtQgJAYgFAVQgGAVAAANQAAAGABACQAAAAAAAAQABABAAAAQABAAAAAAQABAAABAAQAGAAAJgJQAIgIALgOQAMgOAKgPIASgbIALgSIACgCIADAAQADAAADACQADACAAAEIAAABIgSAeQgLASgQAUQgPATgQAOQgPAOgPACIgLABQgTAAgHgKgAAQhfQgGgDAAgHIABgDIABgEIAFgLIAEgJQAGgMAJgGQAJgHAJAAQAFAAAEAEQADADAAAGIAAAEIgCAGIgCAGIgEALIgEAJQgFAJgHAEQgHAFgHAAQgHgBgFgEg");
	this.shape_24.setTransform(338.8736,151.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AhcC2QgXgLgOgUQgOgUgBgbQABgTAHgPQAGgQAOgJQANgKATAAQAHAAAIACQAIABAJAEQgNADgJAKQgJAKgFAOQgFAOgBAQQABAUAHAPQAIAPAMAIQANAIAOAAQAhgCAOgPQAOgPAAgWQgBgSgIgUQgIgUgNgSQgOgRgOgUQgNgSgHgWQgEgMgCgLQgCgMAAgKQAAgjARgaQAQgaAcgOQAbgPAjAAIAOABIAPACQAeAGANASQAOASAAAXQgBAWgJAUQgKAVgRANQgRAOgWAAQgIAAgIgCQgIgCgIgEIACAAQALAAAMgKQALgKAJgQQAJgPAGgSQAFgRAAgPQAAgRgHgIQgIgIgNAAQgUABgUAMQgVAMgNAVQgNAVgBAcQAAARAGASQAHASANATIAbAiQANARAHATQAJATABAZQAAAcgRAUQgQAUgZALQgYALgcAAQgcgBgXgLg");
	this.shape_25.setTransform(321.725,152.525);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AhfBmQgIgHAAgIIAAgCQAEgYAIgaQAHgaAIgXQAJgYAIgTQAIgSAGgJQAIgNAKgGQAKgGAIAAQAFAAADADQACADAAAFQgBAHgMAgQgNAggUA6QAWgoAWggQAVgfAVgSQAUgSASgBQALAAAHAFQAHAEAAAJQAAAFgEAJIgIAXQgEAMAAALQAAAGABACQABADAEABIgNADIgLAAQgNAAgIgFQgHgFAAgMQAAgJAFgMQAFgMAKgRQgMAIgPARQgPARgPAWQgPAXgNAWQgOAXgKAUIgPAfQgDAIgEADQgEAEgFAAQgKgBgHgHg");
	this.shape_26.setTransform(281.575,156.075);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("Ag3BmQgLgIgFgNQgFgMABgPQAAgXAHgWQAIgVAKgOQADgFAGgDQAHgCAHAAQALAAAHAEQAIADABAJIgBAFQgGAFgHAOQgHAPgGARQgFASAAAPQgBAMAEAFQAEAFAJAAQAOAAALgLQAMgMAIgSQAJgSAGgUQAEgUABgSQAAgTgHgNQgGgMgOgBQgJABgIAEQgIAEgDAHQgEAFgGACQgGACgGAAQgJAAgHgEQgGgDAAgIQAAgIAHgJQAIgKAMgIQAJgGALgDQAJgEAKAAQAgACAOAUQAPASAAAgQgBAYgIAZQgIAagOAWQgPAWgSAOQgSANgWABQgRgBgLgHg");
	this.shape_27.setTransform(263.5477,156.025);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("Ah6C6QgIgHAAgIQACgYAIgfQAIggAOgnIgCgEIgBgEQAAgDACgCQAAgBABAAQAAgBAAAAQABAAABAAQAAAAABAAIADABIAbhDIAYg1IAPgeQAJgNAJgGQAJgFAIgBQAFAAADADQADADAAAFQAAADgDAKIgMAcIgTA0IgfBRIABAAQAmgBAggUQAggUAUgfQAUghABgmQgBgigRgUQgSgVgfAAQgSAAgRAGQgSAIgPAMQgVATgOAbQgOAbgIAdQgIAcgCAaQgGACgFABIgJACQgMAAgGgKQgGgJgBgQQAAgRAHgUQAGgVANgUQAMgVATgTQATgSAYgNQASgJAVgGQAUgEAVAAQAjgBAaAOQAaAOAPAYQAOAYABAeIgCARQgBAJgDAIQgKAhgUAVQgVAWgaANQgaAMgbAGQgbAFgYABIgNgBIgXBDQgKAggEATQgCAKgFAFQgFADgFAAQgKAAgHgIg");
	this.shape_28.setTransform(241.875,152.45);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgNCUQgIgLAAgSIAAgLIACgLQgKAQgLANQgLANgMAJQgMAIgLAAQgYgBgKgOQgJgPAAgZQAAgSAEgSQAEgTAGgQQAFgRAFgJQAUglAVgQQAVgQAZABQARgBAOAIQAPAHAIAOIAAgBQAIgMAKgGQAKgHAIAAQAFABADACQACACABAGIgGATIgPAkIgQAtQgJAYgGAVQgFAVgBAOIABAHQABABAAAAQABAAAAABQAAAAABAAQABAAAAAAQAGAAAJgJQAKgJALgNIAVgdIATgbIALgSIACgCIACAAQAEAAACACQADACAAADIAAACIgSAeQgLASgPATQgQAUgQAOQgQAOgPADIgKABQgSgBgIgKgAgbgkQgMAOgLAUQgKAUgHAYQgIAXgEAWQgEAVgBAOQAAAHACAEQABAFADAAIAAAAQAIAAAMgNQALgNAMgVIAagqIAWgsIARggQgHgLgIgGQgJgFgIAAQgNAAgMANgAAGhsQAAAAgBAAQAAAAgBgBQAAAAgBAAQgBgBAAAAIgEgFIgBgCIgBgEIAAgCIABAAIAEgEIAFgFIAQgNIAPgLIABgBIADABQAEACAEAEQAEAFAAAEIAAADIgCACIgPAJIgPAKIgNAJg");
	this.shape_29.setTransform(201.925,151.35);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AhfBmQgIgHAAgIIAAgCQAEgYAIgaQAHgaAIgXQAJgYAIgTQAIgSAGgJQAIgNAKgGQAKgGAIAAQAFAAADADQACADAAAFQgBAHgMAgQgNAggUA6QAWgoAWggQAVgfAVgSQAUgSASgBQALAAAHAFQAHAEAAAJQAAAFgEAJIgIAXQgEAMAAALQAAAGABACQABADAEABIgNADIgLAAQgNAAgIgFQgHgFAAgMQAAgJAFgMQAFgMAKgRQgMAIgPARQgPARgPAWQgPAXgNAWQgOAXgKAUIgPAfQgDAIgEADQgEAEgFAAQgKgBgHgHg");
	this.shape_30.setTransform(178.075,156.075);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AhDCTQgJgLABgRQAAgUAHgYQAHgXAKgXQAJgXAKgRIAPgbQAIgMAJgGQAKgGAIAAQAFAAADACQACADAAAGQAAADgGAQIgOAkIgQAtQgJAYgFAVQgGAVAAANQAAAGABACQAAAAAAAAQABABAAAAQABAAAAAAQABAAABAAQAGAAAJgJQAIgIALgOQAMgOAKgPIASgbIALgSIACgCIADAAQADAAADACQADACAAAEIAAABIgSAeQgLASgQAUQgPATgQAOQgPAOgPACIgLABQgTAAgHgKgAAQhfQgGgDAAgHIABgDIABgEIAFgLIAEgJQAGgMAJgGQAJgHAJAAQAFAAAEAEQADADAAAGIAAAEIgCAGIgCAGIgEALIgEAJQgFAJgHAEQgHAFgHAAQgHgBgFgEg");
	this.shape_31.setTransform(164.1736,151.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AhYBsQgOgSABgdQAAgaAHgaQAGgZAJgVQAIgWAHgKQAIgMAKgGQAJgGAIAAQAFAAADACQADADAAAGQAAADgDAIIgHAWIgLAnIgKAsQgEAYAAATQAAANADAIQADAHAHABQAIgBANgQQANgPAOgaQAOgZANgeQAOgdAIgcQAIgcABgVIgBgGIAAgHQAUAEAJAOQAJANAAAVQgBAWgIAbQgKAagPAbQgPAbgTAWQgTAWgUAOQgUANgUAAQgggBgMgRg");
	this.shape_32.setTransform(146.7991,154.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AhDCTQgJgLABgRQAAgUAHgYQAHgXAKgXQAJgXAKgRIAPgbQAIgMAJgGQAKgGAIAAQAFAAADACQACADAAAGQAAADgGAQIgOAkIgQAtQgJAYgFAVQgGAVAAANQAAAGABACQAAAAAAAAQABABAAAAQABAAAAAAQABAAABAAQAGAAAJgJQAIgIALgOQAMgOAKgPIASgbIALgSIACgCIADAAQADAAADACQADACAAAEIAAABIgSAeQgLASgQAUQgPATgQAOQgPAOgPACIgLABQgTAAgHgKgAAQhfQgGgDAAgHIABgDIABgEIAFgLIAEgJQAGgMAJgGQAJgHAJAAQAFAAAEAEQADADAAAGIAAAEIgCAGIgCAGIgEALIgEAJQgFAJgHAEQgHAFgHAAQgHgBgFgEg");
	this.shape_33.setTransform(131.3736,151.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgrDRIgEAAQgdgGgLgXQgMgWAAggQAAgcAGgfQAGgeAJgeQAIgdAIgZIAOgqQAFgTADgOQACgOAAgJQAAgKgCgDQgDgDgFAAQgMABgPARQgPARgNAaQgNAagKAcQgIAdAAAWQAAAIACAHIgMAEIgKACQgMgBgHgKQgGgLAAgQQABgRAFgWQAHgVALgWQANgWARgTQASgSAWgMQAXgLAbgBQAPAAAJAJQAKAJgBAYIgBAYQgBANgEAPQgCAPgIAcIgQA+QgJAigFAhQgHAiAAAZQAAAWAGAKQAFALAMAAQAOgBASgSQARgSASgeQATgfARgmQARgmAOgnQAOgoAHgmQAIglAAgeQAAgNgBgKQgCgLgEgHQAdAFAOATQANAUAAAfQgBAegKAlQgKAlgTAmQgSAmgXAkQgXAkgZAcQgZAdgXAQQgXARgTAAIgEAAg");
	this.shape_34.setTransform(107.9,150.925);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AkVEkIgSgBIgRgCIgUgFQgRgEgUgKQgTgKgMgSQgHgMgCgNQgBgNAFgQQABgDAIgMQAHgNAUgKQAagLAjAEQAkAEAtAVIA9AbIAoARIAPgNQAPgNAUgYQAUgYATgiQASghAIgrQAIgpgJgyQgBgCABgDQABgCADgCQAPgHAMgKQANgLAIgNQAJgWgGgNQgGgOgJgHIgJgIIgFgFIgFAKIgFAKIgUAsIgSAgIgIANQgBADgDABQAAABgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAIgDgBIgDgBQgDgCgBgEQgBgDABgFIAIgNIASggIAVgrIAGgNIAEgLQgQgMgFgNQgFgNABgJQABgQAIgMQAIgNALgGQAGgDAHACQAHABAGAFQAHAFACASQABARgPAqIAIAGIASANIAMAKQAPALAIAMQAHALACAIQABABABAOQABAOgLASQgLATghAPQAKAeACAZQACAbgGAZIAAABIABABIABgBIABAAQALgKAMgPIAaghQAQgVANgVIAVgiIAIgOQACgEAEgBQAEgBAEACQADADABADQABAEgCAEIgIAOIgVAjIgdArIgcAkQgNAPgMAMIgOALIgNAIQgSAqgYAeQgZAfgUAQIgVARQA8ASA0AKQA0AJAzABIAbAAIAagCIARgDQAJgBAJgDQAngMAdgRQAdgSAUgTQATgTAKgNIALgPQACgCADAAIADABQAQAOgCAOQgBANgHAJIgIAKQgUASgWANQgWANgSAIQgSAIgIACQgeAKgiAGQghAFglAAQhIABg/gLQg+gLg4gTQgfATguAMQgrANgxAAIgHAAgAlnCrQgRAGgFAJQgFAIABABQgEAKAAAJQABAJAFAIQAJANAOAIQAQAIANADQATAGAOABIAOABQAmAAAhgKQAhgLAcgSIhTghQgjgQgUgIQgXgIgSAAIgDAAQgQAAgJAEgAAJkOIgBABQgFACgFAHQgFAIgBAKIABAAQAAAIADAGQADAHAFAGIAEgLIADgLQAEgSgBgHQgBgHgBAAIgBgBIgBAAIgBgBIAAABg");
	this.shape_35.setTransform(894.7981,75.5784);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AhACsQgIAAgMgCQgNgDgQgJQgPgIgLgRQgHgJgDgLQgDgLAAgNQgCgUADgTQAEgUAHgRQAKgcAMgUQALgTAEgEQARgaASgSQASgSAPgMQAUgQAOgHIAOgIQAVgIARAAQARgBAMAHIAJAHQAGAGAEALQADAKgCALQgCALgHANQgEAIgPARQgQAQgeAUQgXANgYAJQgaAJgbAEQgOAdgGASIgGASQgHAYADAUQAFAVAOALQAPAMAZgCQAbgFAXgOQAXgPAQgQQAUgUANgPQALgPAAgCQAVgeANgVIANgXQADgEAEgBQAEgBADACQAEACABAEQABAEgCAEIgOAWQgNAXgVAeIgNATQgMAQgVAUQgdAbgeAPQgcAPgdAAIgHAAgAA7iUQgGABgOAJQgPAJgXAXQgUAWgPAVQgQAVgMAUQAagGAUgJQASgIAOgIIAYgRIAUgSIAMgQIAEgGQAEgLgCgNQgCgMgLgDIAAAAIgGABg");
	this.shape_36.setTransform(875.6303,69.0688);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AADCrQgOgCgNgQQgIgLgBgRQAAgRAEgUIgDAFIgDAFQgbAkgXASQgYASgUAAQgQAAgKgFQgMgFgGgKQgIgLgBgPQgCgQAEgUIAGgXIAEgMIAMgfIANgdIAQgiIAUgnIAJgTIATgnIAMgcQACgEAFgBQAEgBADADQAJAGAIANQAIAMABASQACASgNAWIgKASIgUAoIgUAlIgNAfIgMAdIgHAQQgGAPgCAQQgCAQAIAEQAKADALgHQALgGAIgJQAWgVAXgkQAZgjAYgwIAXgvIAcg4QANgbAHgSQACgEAFgBQAEgBADADQAJAGAJAMQAIAMABASQABASgNAXIgPAbIgcA2IgeBAQgOAhgGAXQgFAWAIAEIAGABQAGAAALgIIAGgFIAIgGQAKgLANgPQAMgPAOgTQARgWANgVIAUghIAIgOQADgEAEgBQAEgBADACQAEADACADQABAEgCAEIgJANIgVAjQgNAVgRAXIgcAkQgNAPgMAMIgOAMIgOAIIgNAEQgHADgJAAIgKgBg");
	this.shape_37.setTransform(847.1833,68.569);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AkVELIgSgBIgRgCIgUgFQgRgEgUgKQgUgKgMgSQgHgMgBgNQgBgNAFgQQAAgDAIgMQAIgNAUgKQAZgLAkAEQAkAEAuAVIA8AbIAoARQAigeAagjQAZgkASghQARghAJgZQgWAegVATQgWATgTAGIgLACIgKACQgGAAgHgCIgLgFQgUgKgKgTQgJgTABgaQACggAPgkQAPglAbglQAbgmAfgaQAfgaAcgNQAZgJASABQASAAAMAJQAHAGADAHQAEAHACAHIAKgTIAHgQQACgEAEgBQAEgBAEADQAIAFAJANQAJAMAAARQACASgOAYIgLAVIgWArIgaA2IgXA1IgBADIgCADQgIAVgBAOQgCANAGACIAGABQAGAAALgIIAOgLQALgLAMgPIAaghIAegrIAVgiIAHgOQACgEAFgBQAEgBADACQAEACABAEQABAEgCAEIgIAOIgVAjIgeAsQgOATgNAQQgOAPgMAMIgOAMIgOAIQgCACgPAEQgPAEgSgHQgLAUgQAXQgQAXgWAXIgHAIIgRAQIgUARQA9AUA3AJQA5AKAyABIAbAAIAbgCIARgDQAIgBAJgDQAngMAegRQAdgSATgTQAUgTAJgNIALgPQACgCAEAAIADABQAPAOgBAOQgBANgHAJIgIAKQgUASgWANQgWANgSAIQgTAIgIACQgeAKghAGQghAFglAAQhJABhDgMQhBgMg5gSQgeATgqANQgoANgwAAIgHAAgAloCSQgQAGgFAJQgFAIAAABQgHAVAKAPQAIANAPAIQAPAIANADQAUAGANABIAPABQAmAAAhgKQAggLAcgSQgvgSgjgPQgjgQgUgIQgYgIgRAAIgEAAQgPAAgKAEgAA6juQgGACgNAJQgNAJgXAXQgKANgOARIgfAoIgMASIgcAsQgOAagLAbQgKAaADASQACAHADAFQAEAEAGABQAFABAGAAQAFAAAFgCQAVgIAYgYQAYgXAagpIATgfIAPgaIAIgPIADgHIAIgRIAJgSQADgHAEgRQAEgSgBgQQgBgRgOgEIAAAAIgGABg");
	this.shape_38.setTransform(813.5858,78.0909);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AAECsQgOgDgNgQQgKgOABgXQACgXAHgZQAHgZAJgWIANgfIAJgQIATglIAUgnIANgYQAFgHABgHQABgFgDgDIgDgBIgCABQgUALgXAcQgXAcgVAiQgWAigQAbIggA6IgbAzIgQAjQgDAFgDACIgHAFQgGACgFgCIgGgCIgHgHQgEgDgCgGQgHgPABgUQABgVAHgWQAHgaAIgSIAQgmIAQgiIATgnIAKgTIATgmIAMgcQADgEADgBQAEgBAEACQAJAHAIAMQAIAMABASQACASgMAXIgKASIgVAoQgMAWgHAOIgOAgIgNAdIATgjIAUgkQATghATgbIAigyQATgaARgQQASgQAOgFIAKgCIAJAAIAJADIAIADQAQAIADAPQAEAOgDAPQgCAPgFAIIgKAUIgPAfIgOAdIgGAMQgQAggOAhQgOAggFAXQgGAXAHAEIAHAAQAFAAAMgIIAGgFIAHgGIAXgZIAbgjQAQgWANgVIAVghIAIgPQADgDADgBQAEgBAEACQAEACABAEQABADgCAFIgIANIgWAjIgeAsIgcAkQgNAQgLALIgPAMQgGAFgHADIgMAFQgIADgIAAIgLgBg");
	this.shape_39.setTransform(784.2763,68.6221);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AhJDRQgPgCgNgQQgKgPACgXQABgWAIgZQAHgZAJgVIAOghIAXguIAeg7IAWgxQACgEAEgBQAEgBAEADQAJAFAIANQAJAMAAASQACASgOAXIgOAbIgcA2IgdBAQgOAhgGAXQgGAWAIAEIAGABQAGgBALgHIAOgLQALgLALgPQANgPANgTIAegrIAVgiIAIgOQACgEAEgBQAEgBAEACQADACABAEQABAEgCAEIgIAOIgVAjQgNAVgRAXQgOAUgNAQQgNAPgLALIgPANIgOAIIgNAEQgHADgJAAIgKgBgAAWiZIgFgCQgEgBgDgEQgEgDADgEQAEgEAIABQAJAAAKgGQAKgHAGgIQAHgIAIgFIAHgDQAHgCAJAAQAIABAHAKQAEAHgJANQgJANgVAJQgMAFgQAAQgLAAgNgCg");
	this.shape_40.setTransform(762.1518,64.7833);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("ABFCsQgQgDgNgQQgKgOABgXQACgXAHgZQAIgZAJgVIAOggIAIgQIATglIAUgnIANgYQAFgHABgHQABgFgDgDIgDgBIgDABQgMAGgPAPQgOAPgQAYQgUAfgSAkIgiBEIgHANIgPAcIgMAVIgLARIgJAKIgFAEIgFADIgFABQgLABgGgEIgFgFQgNgVAFggQAFgfAMgfIAUgtIAKgUIAWgqQAMgYAKgQQAFgHABgHQACgFgEgDIgBgBIgCABQgKAEgPAPQgQAPgUAfQgVAggTAmIgjBFIgKATIgLAYIgFALQgNAZgIANQgIAMgFAFQgFAEgDABQgGACgEgCIgGgCQgFgDgDgEQgDgDgCgGQgIgPABgUQABgVAHgWQAIgZAHgTIARgmIAQgiIATgnIAKgTIATgmIAMgcQACgEAEgBQAEgBAEACQAIAHAIAMQAIAMACASQABASgMAXIgKASIgVAoIgTAlIgHAQIgQAjQgIASgDANIAAABIAAgBIAFgKIALgVIAJgTQAQghAUglQATgmAVghQAVggASgTQATgSARgGIAJgCIAIAAIAJADIAJADQAPAIAEAPQAEAOgCAPQgDAPgFAIIgNAaIgSAjIgIASIgcA4QgNAdgHAUIAFgHIAFgJIAOgbIAGgNIAjhEQASglAVggQALgRALgNQAKgMAKgJQAJgIAIgFQAJgFAIgCIAIgBIAIAAIAJADIAIADQAQAIAEAPQAEAOgDAPQgCAPgFAIIgLAUIgPAfIgOAdIgGAMIgeBBQgNAggGAXQgGAXAIAEIAGAAQAFAAAMgIIAGgFIAHgGIAYgZQANgQANgTQARgWANgVIAVghIAHgOQADgEAEgBQAEgBADACQAEACABAEQABAEgCAEIgIANIgVAjIgeAsIgcAkQgNAQgMALIgOAMIgOAIIgMAFQgIADgIAAIgKgBg");
	this.shape_41.setTransform(732.8358,68.6221);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgnClIgDAAIgEgBIgOgEQgKgEgNgKQgNgKgKgSQgGgNgDgOQgDgOACgQQADgoAPggQAOggAPgVIAUgbQARgVARgOQAQgNAOgHIALgGQAJgFAJgDQAngLATATQAJAIAEAMQADAMAAASIgCAPIgCAKQAEAVgEAbQgEAcgMAiQgRAvgXAfQgWAfgdAOQgNAFgMACIgRACIgEAAgABRiLQgFAAgKAFQgKAGgQAPQgjAngVAlQgXAlgKAXIgLAZQgFANgCAOQgDAOAAALQAAAUAKAMQAKAMATABIAOgCQAIgCAJgFQATgLAQgSQAOgSAMgVQAKgWAHgTQASgzAAgbQAAgcgIgKQgHgJgGgCIgIgCQgEgBgDgDQgCgDAAgEQAAgEADgDQADgDAEABIAKACQAJACAKAKQAAgJgCgHQgCgIgFgGQgBAAAAgBIAAAAIgCAAIgEAAg");
	this.shape_42.setTransform(697.4281,68.8649);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AkSGQQgUgCgTgGQgdgIgMgOQgMgNgCgLQgDgOAFgPQAFgOANgMQANgLARgHQASgHAVgCQAZgDAbADQAbAEAdAJIBBAWIA8ATQBIgvA7hEQA8hFAnhPQAmhPAJhQQAHhEgQgvQgQgvgcgfQgbgegdgQQgdgQgUgGIgVgHQgagFgUgCQgTgCgFAAQgpAAgoAHQgoAHgmAOQgsAQgmAZQglAYgdAfQgnArgRAvQgRAvAIAwQAIAwAeAeQAdAfA0ANQATAFASABQASACAPAAIAlhKIAxhgIAuhcIAdg+QACgFAEgBQAEgBAEADQAIAGAJANQAIAMABASQAAARgMAXIgOAcIgfA+IgnBMIgiBDQAPgCASgEQASgEATgHIAYgJIAVgKQAegTALgZQAMgZABgUQABgVAAgIQABgMAHgCQAFgCAHACIAGAEIADACQAEADACAGQACAGABAFIAAAEIgBALQgEAagMAVQgMAWgVARQgfAbgzARQgZAJgXAEQgXAEgQACIgDAGIgCAFQgZA2gPAmQgOAmACASQABAEgCACQgCACgDAAQgJgBgIgGQgHgFgGgKQgHgPABgUQAAgSAGgWQAGgTAGgQIALgfIgegCQgRgCgSgFQg5gOgigjQgigjgJg3QgEgaADgaQACgaAKgbQAJgZAPgYQAPgYAUgWQAfghAngaQAogaAugRQAygSA2gHQA1gHA1AFIAWADQAUADAfAKQAfAKAiATQAeARAXAXQAXAWAQAbQATAiAJAoQAIAogDAuQABAEgDAWQgCAXgKAmQgKAkgVAvQgTApgbAmQgaAnggAjQgeAggjAcQgkAdgnAZIA0ANIAzAMQAsAKAmAGQAmAGAgABQAkACAbgEQAbgEASgJIAIgGIAIgGIAFgIQACgFABgEQABgIgDgHQgCgGgFgEIgDgCIgDgCQgHgFgFgHQgEgGAEgJQAHgMAKACQAKACAEADIAEADIAHAGQAKAMABASQABAIgCAGIgCAHQgDAQgKALQgKAMgPAIQgUALgeAEQgdAFgngBQgggDgngFQgngGgtgJIg8gPQgfgIghgKIgQAJIgRAJQgbAOggAJQgfAJghAFQgbACgXAAQgWAAgVgCgAkwEhQgTAHgLAKQgJAIgEAJQgDAKACAJQADAKAKAJQALAIARAEQAPAEASACQAQADASAAQAsAAArgNQArgNApgXIg0gRQgcgJgcgKQgXgIgUgDQgUgEgRAAQgbAAgUAHg");
	this.shape_43.setTransform(657.017,64.3413);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AAECsQgOgDgNgQQgKgOABgXQACgXAHgZQAHgZAJgWIANgfIAJgQIATglIAUgnIANgYQAFgHABgHQABgFgDgDIgDgBIgCABQgUALgXAcQgXAcgVAiQgWAigQAbIggA6IgbAzIgQAjQgDAFgDACIgHAFQgGACgFgCIgGgCIgHgHQgEgDgCgGQgHgPABgUQABgVAHgWQAHgaAIgSIAQgmIAQgiIATgnIAKgTIATgmIAMgcQADgEADgBQAEgBAEACQAJAHAIAMQAIAMABASQACASgMAXIgKASIgVAoQgMAWgHAOIgOAgIgNAdIATgjIAUgkQATghATgbIAigyQATgaARgQQASgQAOgFIAKgCIAJAAIAJADIAIADQAQAIADAPQAEAOgDAPQgCAPgFAIIgKAUIgPAfIgOAdIgGAMQgQAggOAhQgOAggFAXQgGAXAHAEIAHAAQAFAAAMgIIAGgFIAHgGIAXgZIAbgjQAQgWANgVIAVghIAIgPQADgDADgBQAEgBAEACQAEACABAEQABADgCAFIgIANIgWAjIgeAsIgcAkQgNAQgLALIgPAMQgGAFgHADIgMAFQgIADgIAAIgLgBg");
	this.shape_44.setTransform(573.6763,68.6221);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AALCrQgOgCgNgQQgIgMAAgSQgBgTAFgVQgYAigWAUQgXAUgUAHIgKACIgKACQgHAAgGgCIgMgFQgUgKgJgTQgKgTACgbQABggAQgkQAPgkAaglQAbgmAfgaQAfgaAegNQAXgJASABQATAAAMAJQAGAGAEAHQAFAHABAHIAJgTIAHgQQACgEAEgBQAEgBAEADQAJAFAJANQAIAMABASQABARgOAYIgOAbIgcA2QgQAhgOAgQgOAggGAXQgGAXAIADIAGABQAGAAALgIIAHgFIAHgGQALgLANgOIAagjIAdgrIAVghIAIgOQACgDAEgCQAEgBAEACQAEADABADQABAEgDAEIgIANIgVAjIgeAsIgbAkQgNAPgMAMIgPAMQgHAFgGADIgNAFQgHACgJAAIgLgBgAAfiPQgGACgOAJQgMAJgWAYQgMAMgOARIgfAoIgMASIgbArQgPAagKAbQgKAbADASQABAHAEAFQAEAEAGABQAEABAGAAQAFAAAGgCQAUgHAYgZQAYgYAbgpIAMgRIAJgRIAJgPIAEgJIAMgXIAQgfIAHgZQAEgSgCgQQgBgRgNgEIAAAAIgGABg");
	this.shape_45.setTransform(542.8541,68.5989);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("Ag2DEQgPgCgNgQQgKgPABgXQACgWAHgZQAHgZAJgWIAOggIAFgJIAKgTIAKgYQAHgNgDgIQgEgJgIgGIgJgIIgFgEIgJATIgWAsIgSAfIgIANQgCAGgGAAIgDgBIgDgBQgDgCgBgEQgBgEADgEIAHgMIARggIAWgrIAFgNQADgFABgGQgQgMgEgNQgFgNABgJQABgQAHgMQAIgNANgGQAHgDAGACQAHABAFAEQAHAGACASQACARgPAqIAEAEIAHAGIAMAJIAOAKQAPALAGALQAIAMABAIQACAOgDAQQgEAPgFALIgFAMIgbA+QgPAfgHAXQgHAWAHADIAHABQAFAAAMgIIAGgFIAHgGQAKgLAMgOQANgQAOgTQAQgWANgVIAVgiIAJgOQACgDAEgBQADgBAEABQAEADABADQABAEgCAEIgIAOIgVAjQgOAVgRAXIgbAkQgNAPgMALIgOANQgHAFgGACQgBACgLADQgIADgJAAIgKgBgAg3ivQgFACgGAIQgFAHAAALQAAAIADAGQADAHAGAGIAEgLIAEgLQAEgSgCgIQgBgGgBgBIAAAAIgBgBIgBAAIgCABg");
	this.shape_46.setTransform(516.8375,66.0802);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AADCrQgOgCgNgQQgIgLgBgRQAAgRAEgUIgDAFIgDAFQgbAkgXASQgYASgUAAQgQAAgKgFQgMgFgGgKQgIgLgBgPQgCgQAEgUIAGgXIAEgMIAMgfIANgdIAQgiIAUgnIAJgTIATgnIAMgcQACgEAFgBQAEgBADADQAJAGAIANQAIAMABASQACASgNAWIgKASIgUAoIgUAlIgNAfIgMAdIgHAQQgGAPgCAQQgCAQAIAEQAKADALgHQALgGAIgJQAWgVAXgkQAZgjAYgwIAXgvIAcg4QANgbAHgSQACgEAFgBQAEgBADADQAJAGAJAMQAIAMABASQABASgNAXIgPAbIgcA2IgeBAQgOAhgGAXQgFAWAIAEIAGABQAGAAALgIIAGgFIAIgGQAKgLANgPQAMgPAOgTQARgWANgVIAUghIAIgOQADgEAEgBQAEgBADACQAEADACADQABAEgCAEIgJANIgVAjQgNAVgRAXIgcAkQgNAPgMAMIgOAMIgOAIIgNAEQgHADgJAAIgKgBg");
	this.shape_47.setTransform(488.4333,68.569);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AkSGQQgUgCgTgGQgdgIgMgOQgMgNgCgLQgDgOAFgPQAFgOANgMQANgLARgHQASgHAVgCQAZgDAbADQAbAEAdAJIBBAWIA8ATQBIgvA7hEQA8hFAnhPQAmhPAJhQQAHhEgQgvQgQgvgcgfQgbgegdgQQgdgQgUgGIgVgHQgagFgUgCQgTgCgFAAQgpAAgoAHQgoAHgmAOQgsAQgmAZQglAYgdAfQgnArgRAvQgRAvAIAwQAIAwAeAeQAdAfA0ANQATAFASABQASACAPAAIAlhKIAxhgIAuhcIAdg+QACgFAEgBQAEgBAEADQAIAGAJANQAIAMABASQAAARgMAXIgOAcIgfA+IgnBMIgiBDQAPgCASgEQASgEATgHIAYgJIAVgKQAegTALgZQAMgZABgUQABgVAAgIQABgMAHgCQAFgCAHACIAGAEIADACQAEADACAGQACAGABAFIAAAEIgBALQgEAagMAVQgMAWgVARQgfAbgzARQgZAJgXAEQgXAEgQACIgDAGIgCAFQgZA2gPAmQgOAmACASQABAEgCACQgCACgDAAQgJgBgIgGQgHgFgGgKQgHgPABgUQAAgSAGgWQAGgTAGgQIALgfIgegCQgRgCgSgFQg5gOgigjQgigjgJg3QgEgaADgaQACgaAKgbQAJgZAPgYQAPgYAUgWQAfghAngaQAogaAugRQAygSA2gHQA1gHA1AFIAWADQAUADAfAKQAfAKAiATQAeARAXAXQAXAWAQAbQATAiAJAoQAIAogDAuQABAEgDAWQgCAXgKAmQgKAkgVAvQgTApgbAmQgaAnggAjQgeAggjAcQgkAdgnAZIA0ANIAzAMQAsAKAmAGQAmAGAgABQAkACAbgEQAbgEASgJIAIgGIAIgGIAFgIQACgFABgEQABgIgDgHQgCgGgFgEIgDgCIgDgCQgHgFgFgHQgEgGAEgJQAHgMAKACQAKACAEADIAEADIAHAGQAKAMABASQABAIgCAGIgCAHQgDAQgKALQgKAMgPAIQgUALgeAEQgdAFgngBQgggDgngFQgngGgtgJIg8gPQgfgIghgKIgQAJIgRAJQgbAOggAJQgfAJghAFQgbACgXAAQgWAAgVgCgAkwEhQgTAHgLAKQgJAIgEAJQgDAKACAJQADAKAKAJQALAIARAEQAPAEASACQAQADASAAQAsAAArgNQArgNApgXIg0gRQgcgJgcgKQgXgIgUgDQgUgEgRAAQgbAAgUAHg");
	this.shape_48.setTransform(443.067,64.3413);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgEAXQgFgBgGgDQgFgEgCgKQAAgOAIgHQAJgGAIABQAIABAFAEQAFAFABAIQABAIgFAIQgFAIgMACIgFAAg");
	this.shape_49.setTransform(369.3063,83.0933);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("ADYGSIgMgEQgbgHgSgRQgSgQgJgYQgKgZgBggQgCggAGgnQAGgfAKgjQAKgjAPgnQALgdAMgaIAVguIAfg/IArhTIAuhYIAnhMQglAlgkApQgkAoghAsQgiAtggAwQgfAvgdAxQgfA1gVApIggBEIgNAgIAAABQgBAEgCACQgBADgDABQgGAAgEgCIgFgDQgegdgBg0QgCg0AThAQATg/AchCQAdhBAfg6QAfg6AYgnQgdAdgfAmIg+BNIg2BIIgoA3IgQAWIAAABQggAtgmAvQgkAvgqAuQgqAtguAmQgmAfglAWQgmAXglANQgcAKgcAEQgbAFgcAAQgfAAgegFQgsgJgmgZQglgXgcgnQgbgjgOgrQgPgrgBgvQgBgZADgYQAEgYAHgXQAHgaAMgXQAMgXAPgVQARgWAVgTQAUgUAZgQQAPgJARgIQAQgJASgHIAYgJQAWgHAdgGQAegGAeADIAMACQALADAKAKQAKAKgEAUIgBADQgCADgFgBQgCgCgbgGQgagFgrABQgrACgzAUIgUALIgJAFQgXAOgUASQgTASgQAWQgPATgKAVQgLAWgHAXQgHAWgDAXQgDAXABAXQABArAOApQANAoAYAhQAbAiAiAWQAiAXApAHQAoAIAogDQApgDAogPQAkgMAkgVQAkgVAkgeQAugmAogsQApgtAlgvQAkguAhgtIAZgkIA4hLQAigtAlgwQAmgvAkgmQAkgmAagQIACgBIACAAQALgEAJAHQAIAIADAMQABALgDAKQgDAKgEAHIgEAHQhOCBgpBgQgpBfgOBBQgPBAgBAlIAghDQAVgoAcgwQAdgzAggwQAggvAjgtQArg5AugzQAtgyAwgtIAEgCQADgCAGACQAIAHAJAMQAIANABASQABARgNAYIgOAcIgjBAIgqBRIgnBMIgZAzIgMAbQgNAbgQAqQgRArgOAwQgPAwgFAsQgFAtAMAeQALAeAjAHIAUABQAMAAAOgDQAJgCAKgGQALgGAKgLIADgFIAEgEQgVgJgIgPQgIgQABgRQACgQAGgJQAHgIAGgDIAHgCQALgCAHACQAGACAEAEQAJAKACALQACALAAADQAAAKgCAJIgEASQAUgBAigHIBKgQQAygMA1gKQA1gLAzgHQA9gGAoAFQAoAFAUAQQAMAKAGAOQAGANAAARIAAAKQgBAHgEAJQgDAKgJALQgJAKgSAGIgIABIgEAAQgGAAgFgEQgFgEgCgJQgBgJAHgFQAGgEAJgDIAEgBIADgBQAKgDAJgMQAJgNgGgRIgFgJIgIgIQgRgOgkgEQglgEg3AGQgyAGg2ALIhmAXIhIAQQggAGgVACIgLABIgDgBIgFAKIgGAIQgKALgNAJQgNAIgPAEIgSAEIgQABQgRgBgKgCgAE7EPIgGAEQgEAEgCAMQgBAJAEALQAFALAPAGQADgIABgJIABgTQAAgKgCgEIgDgEIgDgCIgFgBIgDAAg");
	this.shape_50.setTransform(330.2464,63.9417);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgnClIgDAAIgEgBIgOgEQgKgEgNgKQgNgKgKgSQgGgNgDgOQgDgOACgQQADgoAPggQAOggAPgVQAPgWAFgFQARgVARgOQAQgNAOgHIALgGQAJgFAJgDQAngLATATQAJAIAEAMQADAMAAASIgCAPIgCAKQAEAVgEAbQgEAcgMAiQgRAvgXAfQgWAfgdAOQgNAFgMACIgRACIgEAAgABRiLQgFAAgKAFQgKAGgQAPQgjAngVAlQgXAlgKAXIgLAZQgFANgCAOQgDAOAAALQAAAUAKAMQAKAMATABIAOgCQAIgCAJgFQATgLAQgSQAOgSAMgVQAKgWAHgTQASgzAAgbQAAgcgIgKQgHgJgGgCIgIgCQgEgBgDgDQgCgDAAgEQAAgEADgDQADgDAEABIAKACQAJACAKAKQAAgJgCgHQgCgIgFgGQgBAAAAgBIAAAAIgCAAIgEAAg");
	this.shape_51.setTransform(203.6281,68.8649);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("Ag2DEQgPgCgNgQQgKgPABgXQACgWAHgZQAHgZAJgWIAOggIAFgJIAKgTIAKgYQAHgNgDgIQgEgJgIgGIgJgIIgFgEIgJATIgWAsIgSAfIgIANQgCAGgGAAIgDgBIgDgBQgDgCgBgEQgBgEADgEIAHgMIARggIAWgrIAFgNQADgFABgGQgQgMgEgNQgFgNABgJQABgQAHgMQAIgNANgGQAHgDAGACQAHABAFAEQAHAGACASQACARgPAqIAEAEIAHAGIAMAJIAOAKQAPALAGALQAIAMABAIQACAOgDAQQgEAPgFALIgFAMIgbA+QgPAfgHAXQgHAWAHADIAHABQAFAAAMgIIAGgFIAHgGQAKgLAMgOQANgQAOgTQAQgWANgVIAVgiIAJgOQACgDAEgBQADgBAEABQAEADABADQABAEgCAEIgIAOIgVAjQgOAVgRAXIgbAkQgNAPgMALIgOANQgHAFgGACQgBACgLADQgIADgJAAIgKgBgAg3ivQgFACgGAIQgFAHAAALQAAAIADAGQADAHAGAGIAEgLIAEgLQAEgSgCgIQgBgGgBgBIAAAAIgBgBIgBAAIgCABg");
	this.shape_52.setTransform(184.4375,66.0802);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgJESQgPgCgNgRQgJgLAAgTQAAgTAFgUQgZAhgWAUQgXAUgUAHIgKADIgKABQgGAAgHgCIgMgEQgUgLgJgTQgKgTABgbQACgfAQglQAPglAaglQAbglAfgZQAfgbAegMQAYgJARAAQASAAANAKQAHAGAEAHQAEAHABAIIAzhiIAthXQATgnAIgSQACgEAEgBQAEgCAEADQAJAGAIAMQAIAMABASQABASgMAXIgPAcIgjBBIgqBRIgnBLIgZAzIgbA9QgMAdgFAUQgEAVAGADIAGAAQAGAAALgHQAHgEAHgIQALgKAMgPIAbgiQAQgXANgVIAVghIAIgPQACgDAEgBQAEgBAEACQAEACABAEQABADgCAEIgIAPIgVAiIgeAtIgcAjQgNAQgMALIgOAMQgIAGgGACIgNAFQgHADgJAAIgJgBgAAJgoQgGABgMAJQgOAKgWAWIgZAeIggAnIgMASQgMASgPAaQgPAbgKAbQgKAaADASQABAIAEAEQAEAFAGABQAFABAFgBQAFAAAGgCQAUgHAYgYQAYgZAbgoIAOgVIALgTIAHgNIADgHIAMgZIAQghQAEgJADgQQADgPgBgPQgCgPgMgEIgBAAIgGABg");
	this.shape_53.setTransform(157.3939,58.3082);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AhACsQgIAAgMgCQgNgDgQgJQgPgIgLgRQgHgJgDgLQgDgLAAgNQgCgUADgTQAEgUAHgRQAKgcAMgUQALgTAEgEQARgaASgSQASgSAPgMQAUgQAOgHIAOgIQAVgIARAAQARgBAMAHIAJAHQAGAGAEALQADAKgCALQgCALgHANQgEAIgPARQgQAQgeAUQgXANgYAJQgaAJgbAEQgOAdgGASIgGASQgHAYADAUQAFAVAOALQAPAMAZgCQAbgFAXgOQAXgPAQgQQAUgUANgPQALgPAAgCQAVgeANgVIANgXQADgEAEgBQAEgBADACQAEACABAEQABAEgCAEIgOAWQgNAXgVAeIgNATQgMAQgVAUQgdAbgeAPQgcAPgdAAIgHAAgAA7iUQgGABgOAJQgPAJgXAXQgUAWgPAVQgQAVgMAUQAagGAUgJQASgIAOgIIAYgRIAUgSIAMgQIAEgGQAEgLgCgNQgCgMgLgDIAAAAIgGABg");
	this.shape_54.setTransform(126.3303,69.0688);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AmhGHQgYgKgKgUIgEgJQgEgIgBgNIAAgNIAFgSQAIgQAJgGIAJgGIAGgCQAHgBAHACQAHACADALQACAKgFAFQgGAFgIADIgEABIgEABQgFADgEAGQgFAFAAAIIAAAHQAAAGAFAIQAGAMAPAHQAOAIAWABQAVADAbgDQAbgDAggIQAngIAogNQAogNAjgNQAkgOAagMIAFgDIAFgCQADgdAKgkQAKglARgrIAHgXIAJgXIgOgDIgHgCQgEgBgCgEQgCgDABgFQABgDADgCQADgDAFABIAGACIASADIARgjIAMgaIAIgRIAFgJIAmhNIAthYIAphSQASgkAIgTQACgEAEgBQAEgBAEACQAIAHAIAMQAIAMABASQACASgNAXIgMAYIgeA4IgkBHIgiBDIgXAvIgFAMIgQAiIARAAIASAAQA8gBAtgVQAtgTAfgeQAggbAUgdQATgdAKgTIAJgUQAXg+AAgtQABgsgPgeQgPgegXgSQgWgSgXgIQgWgJgPgDIgQgDIgHgBIgWgCIgNAAQgpgCgoAHQgnAGgkAOQgoAPgjAYQgiAYgbAeQgTAWgOAYQgOAXgKAZIgDANIgDAOQgGAjAFAaQAFAZAIAPIAMAXQAFALgEAEQgFAEgGAAIgHAAIgDAAQgKgCgGgIQgFgIgDgHIgCgIQgHgfABggQABggAKghQAJgfAQgeQAQgdAYgaQAcggAlgZQAkgaAqgQQAvgRAygHQAzgFA1AFIATADQASACAZAJQAiAMAbASQAbATASAZQAaAlAGAyQAGAygPA9QgNA0gaAoQgaAogoAcQgfAWgnAOQgnAPgtAGIgjADIghABIgYAAIgXgBQgRAlgSAuQgSAvgMAqIAGABIAMACQAKADAIAFQAIAFAGAGQANAPADASQADATgJAQQgKASgNAGQgMAGgMABQgKAAgHgCIgIgCQgZgIgLgZQgEgKgCgNQgCgNABgPIgIAEIgMAFQgoASg1ASQg1ATg3AMQgbAGgXADQgXAEgUAAQgkAAgXgLgAAAFdQAAAUAIAHIAIADIAJABQAKgBAHgEQAHgFAFgJQAFgLgCgMQgBgMgKgKQgGgHgJgEQgIgDgLgBIgDgBIgDAAQgGAdAAAUg");
	this.shape_55.setTransform(69.4232,64.2375);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	// Capa_1
	this.instance = new lib.A7x15centimetros_00136();
	this.instance.setTransform(232,544,0.8547,0.8547);

	this.bt = new lib.Symbol8();
	this.bt.name = "bt";
	this.bt.setTransform(480.25,367.2,1.3268,1.3268,0,0,0,155.7,48.4);

	this.instance_1 = new lib.an_Video({'id': 'instance_1', 'src':'videos/video.mp4', 'autoplay':true, 'controls':true, 'muted':false, 'loop':true, 'poster':'', 'preload':true, 'class':'video'});

	this.instance_1.setTransform(487.45,933.8,2.0878,4.9488,0,0,0,200.1,150.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.bt},{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(494.3,903.4,416.49999999999994,774.6999999999999);
// library properties:
lib.properties = {
	id: '2D491E97AE588741B9DB3D9844D8E56D',
	width: 950,
	height: 1781,
	fps: 60,
	color: "#000000",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_1.png?1737997251404", id:"index_atlas_1"},
		{src:"https://code.jquery.com/jquery-3.4.1.min.js?1737997252090", id:"lib/jquery-3.4.1.min.js"},
		{src:"components/sdk/anwidget.js?1737997252090", id:"sdk/anwidget.js"},
		{src:"components/video/src/video.js?1737997252090", id:"an.Video"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['2D491E97AE588741B9DB3D9844D8E56D'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
function _updateVisibility(evt) {
	var parent = this.parent;
	var detach = this.stage == null || this._off || !parent;
	while(parent) {
		if(parent.visible) {
			parent = parent.parent;
		}
		else{
			detach = true;
			break;
		}
	}
	detach = detach && this._element && this._element._attached;
	if(detach) {
		this._element.detach();
		this.dispatchEvent('detached');
		stage.removeEventListener('drawstart', this._updateVisibilityCbk);
		this._updateVisibilityCbk = false;
	}
}
function _handleDrawEnd(evt) {
	if(this._element && this._element._attached) {
		var props = this.getConcatenatedDisplayProps(this._props), mat = props.matrix;
		var tx1 = mat.decompose(); var sx = tx1.scaleX; var sy = tx1.scaleY;
		var dp = window.devicePixelRatio || 1; var w = this.nominalBounds.width * sx; var h = this.nominalBounds.height * sy;
		mat.tx/=dp;mat.ty/=dp; mat.a/=(dp*sx);mat.b/=(dp*sx);mat.c/=(dp*sy);mat.d/=(dp*sy);
		this._element.setProperty('transform-origin', this.regX + 'px ' + this.regY + 'px');
		var x = (mat.tx + this.regX*mat.a + this.regY*mat.c - this.regX);
		var y = (mat.ty + this.regX*mat.b + this.regY*mat.d - this.regY);
		var tx = 'matrix(' + mat.a + ',' + mat.b + ',' + mat.c + ',' + mat.d + ',' + x + ',' + y + ')';
		this._element.setProperty('transform', tx);
		this._element.setProperty('width', w);
		this._element.setProperty('height', h);
		this._element.update();
	}
}

function _tick(evt) {
	var stage = this.stage;
	stage&&stage.on('drawend', this._handleDrawEnd, this, true);
	if(!this._updateVisibilityCbk) {
		this._updateVisibilityCbk = stage.on('drawstart', this._updateVisibility, this, false);
	}
}
function _componentDraw(ctx) {
	if(this._element && !this._element._attached) {
		this._element.attach($('#dom_overlay_container'));
		this.dispatchEvent('attached');
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;